version: "3"

services:
  postgres:
    image: postgres:13
    container_name: arche_pg
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    volumes:
      - pg_data:/var/lib/postgresql/data

  arche:
    build: .
    container_name: arche_app
    ports:
      - "3000:3000"
    links:
      - postgres
    depends_on:
      - postgres

volumes:
  pg_data: {}
