/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */

import * as contextSource from "./pages/api/graphql/context"



declare global {
  interface NexusGenCustomOutputProperties<TypeName extends string> {
    crud: NexusPrisma<TypeName, 'crud'>
    model: NexusPrisma<TypeName, 'model'>
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  NestedStringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  RecipeCreateInput: { // input type
    body: string; // String!
    id?: string | null; // String
    title: string; // String!
  }
  RecipeOrderByInput: { // input type
    body?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    title?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  RecipeUpdateInput: { // input type
    body?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    id?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    title?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  RecipeWhereInput: { // input type
    AND?: NexusGenInputs['RecipeWhereInput'][] | null; // [RecipeWhereInput!]
    body?: NexusGenInputs['StringFilter'] | null; // StringFilter
    id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    NOT?: NexusGenInputs['RecipeWhereInput'][] | null; // [RecipeWhereInput!]
    OR?: NexusGenInputs['RecipeWhereInput'][] | null; // [RecipeWhereInput!]
    title?: NexusGenInputs['StringFilter'] | null; // StringFilter
  }
  RecipeWhereUniqueInput: { // input type
    id?: string | null; // String
    title?: string | null; // String
  }
  StringFieldUpdateOperationsInput: { // input type
    set?: string | null; // String
  }
  StringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    mode?: NexusGenEnums['QueryMode'] | null; // QueryMode
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
}

export interface NexusGenEnums {
  QueryMode: "default" | "insensitive"
  SortOrder: "asc" | "desc"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenRootTypes {
  Mutation: {};
  Query: {};
  Recipe: { // root type
    body: string; // String!
    id: string; // String!
    title: string; // String!
  }
}

export interface NexusGenAllTypes extends NexusGenRootTypes {
  NestedStringFilter: NexusGenInputs['NestedStringFilter'];
  RecipeCreateInput: NexusGenInputs['RecipeCreateInput'];
  RecipeOrderByInput: NexusGenInputs['RecipeOrderByInput'];
  RecipeUpdateInput: NexusGenInputs['RecipeUpdateInput'];
  RecipeWhereInput: NexusGenInputs['RecipeWhereInput'];
  RecipeWhereUniqueInput: NexusGenInputs['RecipeWhereUniqueInput'];
  StringFieldUpdateOperationsInput: NexusGenInputs['StringFieldUpdateOperationsInput'];
  StringFilter: NexusGenInputs['StringFilter'];
  QueryMode: NexusGenEnums['QueryMode'];
  SortOrder: NexusGenEnums['SortOrder'];
  String: NexusGenScalars['String'];
  Int: NexusGenScalars['Int'];
  Float: NexusGenScalars['Float'];
  Boolean: NexusGenScalars['Boolean'];
  ID: NexusGenScalars['ID'];
}

export interface NexusGenFieldTypes {
  Mutation: { // field return type
    createOneRecipe: NexusGenRootTypes['Recipe']; // Recipe!
    deleteOneRecipe: NexusGenRootTypes['Recipe'] | null; // Recipe
    updateOneRecipe: NexusGenRootTypes['Recipe'] | null; // Recipe
  }
  Query: { // field return type
    recipe: NexusGenRootTypes['Recipe'] | null; // Recipe
    recipes: NexusGenRootTypes['Recipe'][]; // [Recipe!]!
  }
  Recipe: { // field return type
    body: string; // String!
    id: string; // String!
    title: string; // String!
  }
}

export interface NexusGenFieldTypeNames {
  Mutation: { // field return type name
    createOneRecipe: 'Recipe'
    deleteOneRecipe: 'Recipe'
    updateOneRecipe: 'Recipe'
  }
  Query: { // field return type name
    recipe: 'Recipe'
    recipes: 'Recipe'
  }
  Recipe: { // field return type name
    body: 'String'
    id: 'String'
    title: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createOneRecipe: { // args
      data: NexusGenInputs['RecipeCreateInput']; // RecipeCreateInput!
    }
    deleteOneRecipe: { // args
      where: NexusGenInputs['RecipeWhereUniqueInput']; // RecipeWhereUniqueInput!
    }
    updateOneRecipe: { // args
      data: NexusGenInputs['RecipeUpdateInput']; // RecipeUpdateInput!
      where: NexusGenInputs['RecipeWhereUniqueInput']; // RecipeWhereUniqueInput!
    }
  }
  Query: {
    recipe: { // args
      where: NexusGenInputs['RecipeWhereUniqueInput']; // RecipeWhereUniqueInput!
    }
    recipes: { // args
      after?: NexusGenInputs['RecipeWhereUniqueInput'] | null; // RecipeWhereUniqueInput
      before?: NexusGenInputs['RecipeWhereUniqueInput'] | null; // RecipeWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenInputs['RecipeOrderByInput'][] | null; // [RecipeOrderByInput!]
      where?: NexusGenInputs['RecipeWhereInput'] | null; // RecipeWhereInput
    }
  }
}

export interface NexusGenAbstractResolveReturnTypes {
}

export interface NexusGenInheritedFields {}

export type NexusGenObjectNames = "Mutation" | "Query" | "Recipe";

export type NexusGenInputNames = "NestedStringFilter" | "RecipeCreateInput" | "RecipeOrderByInput" | "RecipeUpdateInput" | "RecipeWhereInput" | "RecipeWhereUniqueInput" | "StringFieldUpdateOperationsInput" | "StringFilter";

export type NexusGenEnumNames = "QueryMode" | "SortOrder";

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = "Boolean" | "Float" | "ID" | "Int" | "String";

export type NexusGenUnionNames = never;

export interface NexusGenTypes {
  context: contextSource.Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  inheritedFields: NexusGenInheritedFields;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractResolveReturn: NexusGenAbstractResolveReturnTypes;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
}